version: 2
jobs:
  build:
    docker:
      - image: cr0hn/python3.6-alpine-make:1.0.4

    working_directory: ~/repo

    steps:
      - checkout

      - deploy:
          name: Upload to pypi
          command: make upload-pypi